### ISSUE TITLE
What is the status of the project?

### ISSUE THREAD

**Issue by Ch4s3** [rubygems/adoption-center#50]
I was just wondering if other folks are still pursuing this effort. I really like the idea.

**Comment by qrush** [comment]
Our latest idea is to give this a shot inside of the Rubygems.org Rails
app. @sebasoga said he was going to give it a try.

**Comment by Ch4s3** [comment]
@qrush That sounds like a good idea. @sebasoga anywhere I can pitch in, or any issue over at RubyGems I should look at?

**Comment by Ch4s3** [comment]
Ahh, I found the issue. Maybe this should be noted in the readme? For future issue searches https://github.com/rubygems/rubygems.org/issues/725
